### ISSUE TITLE
Answers of DAN are now irrelevant

### ISSUE THREAD

**Issue by gfraiteur** [gayolGate/gayolGate#2]
I tried DAN on Saturday and the answers were quite relevant.

For instance, if you asked "Who funded the campaign of Zelensky" on Saturday, you would get the name of [Ihor Kolomoyskyi](https://en.wikipedia.org/wiki/Ihor_Kolomoyskyi), which is the right answer.

However today, it will answer things like Illuminati or aliens. It's fun, but it's no longer useful.

**Comment by gfraiteur** [comment]
The weird thing here is that ChatGPT knows about the relationship between Zelensky and Kolomoyskyi, but it seems the DAN personality does not because it lives in a parallel universe where there is no politics...

**Comment by gayolGate** [comment]
This jailbreak won’t be updated for new model, as I’m making a new one called Maximum
